version: '3.9.2'
services:
  redis:
    container_name: redis
    image: redis:7.0.11
    command: redis-server --bind 0.0.0.0
    ports:
      - '6379:6379'
    restart: always
  db:
    container_name: mariadb
    ports:
      - '3307:3306'
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Admin1234!!
      MARIADB_DATABASE: nanogrid
      MARIADB_USER: local_user
      MARIADB_PASSWORD: local_password
    volumes:
      - db:/var/lib/mysql
  backend:
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET="MyS3cr3tK3Y"
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - FRONIUS_URL=https://api.solarweb.com/swqapi/iam/jwt
      - FRONIUS_PVSYSTEMS_URL=https://api.solarweb.com/swqapi/pvsystems
      - FRONIUS_PVSYSTEMS_AGGDATA=flowdata

      - PRODUCTION=false

      - SOCKETIO_SERVER=localhost
      - SOCKETIO_PORT=3000
      - DATABASE_URL=mysql://root:Admin1234!!@db:3306/nanogrid
      - NODE_ENV=development
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
      - /usr/src/app/backend/prisma
  frontend:
    container_name: frontend
    ports:
      - '8080:8080'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
volumes:
  db: